### ISSUE TITLE
Migrationjob fails due to lack of permissions

### ISSUE THREAD

**Issue by YentlFrickx** [drycc/service-catalog#17]
# Bug Report 

**What happened**:
When upgrading the service-catalog, the migration fails with following error: Error: when removing owner references from secrets: secrets "xxx" is forbidden: cannot set an ownerRef on a resource you can't delete.

**What you expected to happen**:
Migration job succeeds

**How to reproduce it (as minimally and precisely as possible)**:
We install the chart using following values (we already had a previous version installed and used):
```
  catalog:
    imageTag: "0.4.3"
    webhook:
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 250Mi
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 250Mi
```
`helm upgrade --install catalog . --namespace service-catalog --create-namespace --values values.yaml`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.1 (OKD 4.9)
- service-catalog version: 0.4.3
- Cloud provider or hardware configuration: on-prem
- Do you have api aggregation enabled? yes
  - Do you see the configmap in kube-system?  yes
  - Does it have all the necessary fields? yes
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values? `helm upgrade --install catalog . --namespace service-catalog --create-namespace --values values.yaml`
- Are you trying to use ALPHA features? Did you enable them? No
